# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tlaberro <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/24 17:41:25 by tlaberro          #+#    #+#              #
#    Updated: 2017/07/25 14:39:30 by tlaberro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAG = -Wall\
	   -Werror\
	   -Wextra\

all:
	@gcc $(FLAG) -o do-op ft_atoi.c ft_putnbr.c ft_putchar.c calcul.c

clean:
	@/bin/rm -f do-op
